services:
  - type: web
    name: csat-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.main:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://csat_user:hkdsCJ9zEjXO0TjdMivgwmdEr0e6SUZb@dpg-d25m5rndiees73c2faqg-a.singapore-postgres.render.com/csat_db
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"

